### ISSUE TITLE
Local Effect Flood - Input layers

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/local-effects#9]
We are defining the new script for flood and the first thing we need is to know how the events that characterize the different climate scenarios will be defined. 

Will they be defined by intensity + probability, as the heat waves are, or by a raster map associated to each time period and RCP?

The implications on the naming of the layers will be that in the first way we can just use the intensity of the associated hazard:

> LE_HD_40C

and in the second one we'd need to identify period, RCP and model:

> LE_HD_historical_1971010101-20001231_ensmean

Please, consider how Heat Waves have been defined (three types of events per RCP and period). Will this be consistent with the other hazards (flood).

**Comment by p-a-s-c-a-l** [comment]
Any progress here? If we want to improve visualisation components as requested [here](https://github.com/clarity-h2020/map-component/issues/59) and [here](https://github.com/clarity-h2020/csis/issues/110)  it would be helpful to agree on a data format of the flood events.

**Comment by p-a-s-c-a-l** [comment]
AFAIK those layer are available in METEOGRID GeoServer, right? So next step would be to create the respective resources *with variables* and add it to the European-level Screening Data Package? Which means, we can close this issue?

**Comment by ghilbrae** [comment]
There are currently no flood-related layers on our geoserver that I'm aware of. 
Some time ago we discussed some issues (https://github.com/clarity-h2020/data-package/issues/19#issuecomment-516398550) regarding the flood layers we've received but we never got clarification on that, although I might have missed it because we have automatized the process of updating/uploading the layers created by @RobAndGo , maybe he has some more information regarding the status of that data.

**Comment by RobAndGo** [comment]
Yes, I have delayed uploading them because it would have resulted in WAY too many resources being shown in the European-wide data package. However, @p-a-s-c-a-l and I are hoping to upload some this, this week with the use of variables in the resource names.

**Comment by p-a-s-c-a-l** [comment]
> There are currently no flood-related layers on our geoserver that I'm aware of.

Hm, that's not good. I though they were available. We need them to proceed with the  respective resources.

> Yes, I have delayed uploading them because it would have resulted in WAY too many resources being shown in the European-wide data package.

There is a big difference between uploading resources to GeoServer (data) and making them available as Resources (meta-data) in CSIS. At CSIS-side we can use "variables" in the meta-data (**Template Resources**) to limit the number of resources you have to enter, but this doesn't mean that you don't have to make **all** layers available in GeoServer ...

Ideally, the layers in GeoServer follow already the naming conventions we are using for EMIKAT Template Resources. The relevant [variables](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/dp_variables/overview) that are currently supported are:

- ${time_period}: 'Baseline', '20110101-20401231', '20410101-20701231', '20710101-21001231'
- ${emissions_scenario}: 'Baseline', 'rcp26', 'rcp45', 'rcp85'
- ${event_frequency}: 'Rare', 'Occasional', 'Frequent'

That means, a concrete Geoserver getMap URI would contain the possible values e.g. `https://...&LAYERS=flood_20110101-20401231_rcp85_Frequent...` and the template resource URI in CSIS would look like `https://...&LAYERS=${time_period}_ ${emissions_scenario}_${event_frequency}_` 

If there are other variables than the three mentioned above, we can support them too.

**Comment by RobAndGo** [comment]
Oh no, I think I might have missed the point of @ghilbrae's message! The flood indices ARE in the GeoServer!! I uploaded them to /clarityftp/europe/hazard_indices/precipitation and I think @LauraMTG processed them. [update: Yes, indeed the indices are there!]

In my post above I was referring to the next step in uploading the corresponding resources into CSIS - it is this last step which I have not done, and am waiting for the variable-names to be implemented.

I hope this cleared things up!

**Comment by p-a-s-c-a-l** [comment]
Ok, where do I find the flood resources? What are possibles variables that we can use to limit the number of resources in CSIS? Is time_period, emissions_scenario and event_frequency enough, or do we need some more?

**Comment by RobAndGo** [comment]
The flood resources (actually just precipitation indices) are here:
**/clarityftp/europe/hazard_indices/precipitation/**
**consecutive-wet-days** - maximum number of consecutive days with at least 1mm precipitation
**RR1mm** - number of days with at least 1mm precipitation
**RR20mm** - number of days with at least 20mm precipitation
**RR90p** - number of days that the 90th percentile of precipitation is exceeded.
**Rx1day** - maximum 1-day precipitation
**RX5day**- maximum 5-day precipitation

To limit the number of resources, use:
a) time_period: 19710101-20001231 (only for the historical or baseline scenario), **20110101-20401231, 20410101-20701231, 20710101-21001231**
b) emissions_scenario: baseline (only for the 1971-2000 time period, **rcp26, rcp45, rcp85**.
c) whether data is an ensemble mean "**ensmean**" or standard deviation "**ensstd**"
d) Since the filename format is the same, one could also use a variable for the index name, e.g. "**consecutive-wet-days**", "**rr1mm**", "**rr20mm**", "**rr90p**", "**rx1day**", "**rx5day**" 

For precipitation there is no event frequency.

**Comment by p-a-s-c-a-l** [comment]
> /clarityftp/europe/hazard_indices/precipitation/

O.K, and on [METEOGRID GeoServer](https://clarity.meteogrid.com/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?4) there are ATM just 20 of them:

![grafik](https://user-images.githubusercontent.com/1788226/70549054-e24b5c00-1b73-11ea-89ec-ddc697395a8d.png)

For testing, this is enough for now. But the missing datasets should be imported by @LauraMTG.

If we use the already available variables for time_period and rcp, then we'll end up with 10 template resources to be created. That's fine for me, no need to introduce additional variables and thus additional complexity just to reduce this 5.

**Comment by LauraMTG** [comment]
Hi, @p-a-s-c-a-l and @RobAndGo 

Yes, all precipitation resources have been available on geoserver for several weeks. 

consecutive-wet-days - maximum number of consecutive days with at least 1mm precipitation
RR1mm - number of days with at least 1mm precipitation
RR20mm - number of days with at least 20mm precipitation
RR90p - number of days that the 90th percentile of precipitation is exceeded.
Rx1day - maximum 1-day precipitation
RX5day- maximum 5-day precipitation

Please use the correct search filter to view it.

**Comment by p-a-s-c-a-l** [comment]
The following Local Effects Flood Input Layers are now available in CSIS:

Name | Description | CSIS | CKAN
-- | -- | -- | --
consecutive-wet-days | maximum number of consecutive days with at least 1mm   precipitation | [CSIS Resource](https://csis.myclimateservice.eu/node/2197) | [CKAN   Resource](https://ckan.myclimateservice.eu/dataset/consecutive-wet-days-cwd)
RR1mm | number of days with at least 1mm precipitation | [CSIS Resource](https://csis.myclimateservice.eu/node/2323) | [CKAN   Resource](https://ckan.myclimateservice.eu/dataset/wet-days-rr1)
RR20mm | number of days with at least 20mm precipitation | [CSIS Resource](https://csis.myclimateservice.eu/node/2326) | [CKAN   Resource](https://ckan.myclimateservice.eu/dataset/very-heavy-precipitation-days-r20mm)
RR90p | number of days that the 90th percentile of precipitation is   exceeded | [CSIS Resource](https://csis.myclimateservice.eu/node/2329) | [CKAN   Resource](https://ckan.myclimateservice.eu/dataset/wet-days-wrt-90th-percentile-of-reference-period)
Rx1day | maximum 1-day precipitation | [CSIS Resource](https://csis.myclimateservice.eu/node/2320) | [CKAN   Resource](https://ckan.myclimateservice.eu/dataset/highest-one-day-precipitation-amount-rx1day)
RX5day | maximum 5-day precipitation | [CSIS Resource](https://csis.myclimateservice.eu/node/2317/) | [CKAN   Resource](https://ckan.myclimateservice.eu/dataset/highest-five-day-precipitation-amount-rx5day)

I've added the Template Resources to   [this Test Data Package](https://csis.myclimateservice.eu/node/1537) and [this Test Study](https://csis.myclimateservice.eu/study/54/step/2193/view/maps). You can view the layers (historical time period) on [this map](https://csis.myclimateservice.eu/apps/map-component/build/DataPackagePreviewMap/?host=https://csis.myclimateservice.eu&study_area=POLYGON%20((14.735388874433%2041.096530514014,%2014.735388874433%2040.508407371315,%2013.837759299902%2040.508407371315,%2013.837759299902%2041.096530514014,%2014.735388874433%2041.096530514014))&datapackage_uuid=14c81c77-a6f2-4419-b916-aad431f6accd&write_permissions=1&grouping_tag=taxonomy_term--eu_gl).

Each resources has two "service path references", one for ENSSTD and one or ENSMEAN. Each reference has two variables, one for time_period and one for RCP. Selection of time period and RCP by the user will be supported as described [here](https://github.com/clarity-h2020/docker-drupal/issues/134).

@RobAndGo Can you please have a look at the resources and update the mata-data (contributors, sources, etc.), if necessary. Thanks.

**Important:**
- [ ] All URIs (service paths) have to be updated after [moving data to ATOS Geoserver](https://github.com/clarity-h2020/ckan/issues/23).

**Comment by RobAndGo** [comment]
Hi @p-a-s-c-a-l 
The historical layers look fine. I also looked at how the resources are represented in your Test Data Package, and it does look neat and tidy.

Does this mean that _I_ can change the existing resources within the European Data Package, using this new variable method? 

If so, would the easiest way to be:
1. Create a new resource for e.g. Summer Days using the variables.
2. Within the resource, define the appropriate time periods and RCPs using the variables, and specify the text, and save.
3. Delete all existing (individual) resources of Summer Days (1 resource per time period/RCP)

**Comment by LauraMTG** [comment]
@negroscuro @stefanon @mattia-leone 

Hi¡

I have just finished processing Europe's DEM at 250m resolution according to Clarity's European grid. It is located in the following ATOS FTP directory.  The file transfer is in progress right now.

clarityftp/europe/eu-dem

I understand that it will now be published on your geoserver.

**Comment by p-a-s-c-a-l** [comment]
> If so, would the easiest way to be:
>1) Create a new resource for e.g. Summer Days using the variables.
>2) Within the resource, define the appropriate time periods and RCPs using the variables, and specify the text, and save.
>3) Delete all existing (individual) resources of Summer Days (1 resource per time period/RCP)

@RobAndGo Yes, but please wait until the following issues have been completed:

- [ ] [Export Geoserver layers from MTG to ATOS](https://github.com/clarity-h2020/ckan/issues/2)
- [x] [Showing and changing presets outside the study group context](https://github.com/clarity-h2020/docker-drupal/issues/134#issuecomment-578190164)

You can also **clone** (duplicate) one of the Template Resources in the Data Package and modify that resource instead of creating an entirely new one. 

![grafik](https://user-images.githubusercontent.com/1788226/73361303-fb83a580-42a4-11ea-8ae8-0fbc0f0e01d8.png)

However, you have to be aware that the 'service paths (references)' (e.g. [Consecutive wet days ENSMEAN](https://csis.myclimateservice.eu/node/2318)) are cloned by *by reference*, not *by value*. So you have to duplicate them first, too, and remove the old referenced references from the cloned resource. If you just edit them, you'll also change them in the original resource.

![grafik](https://user-images.githubusercontent.com/1788226/73361252-e149c780-42a4-11ea-9ed7-d2b31485f73b.png)

**Comment by RobAndGo** [comment]
I have a question. I am currently viewing the template layers created in the "[[TEST] Test Study for Template Resources](https://csis.myclimateservice.eu/study/54/step/2193/view/maps)".

I have selected a layer ("consecutive wet days ENSMEAN") from the menu options on the top-right of the map.

How do I select a scenario, e.g. RCP45 for the time period 2041-2070?

There is a button called "Select Scenario" which suggests that I could select something here. But, when I do click on this button, a reload-symbol appears very briefly to the right of the button and nothing else appears to happen. I am using chrome. What should I be seeing, if I have done things correctly?

**Comment by p-a-s-c-a-l** [comment]
@RobAndGo Hm, I've tested it and it did work:

![scenario-selection](https://user-images.githubusercontent.com/1788226/75024447-b31d6900-5499-11ea-95eb-66acc76151e6.gif)

You can create a new scenario by editing the [study context](https://csis.myclimateservice.eu/study/54/view/context):

![grafik](https://user-images.githubusercontent.com/1788226/75023755-9fbdce00-5498-11ea-9428-adfc173e1e14.png)

**Comment by humerh** [comment]
Request for Input layer "clarity:land_use_grid":

Till now I didn't need the attributes for the city, but for flood calculation the selection of the data for one city is required.
Currently the the attributes are:

```
<clarity:city>248</clarity:city>
<clarity:name>BOLOGNA</clarity:name>
```

but not:

```
<clarity:name>WIEN</clarity:name>
<clarity:code>AT001</clarity:code>

```

"code" is the official  KEY for cities.  We had a lot of problems using "NAME" as key, because NAME often contains national characters, which are NOT uniquely implemented in all components.

For me it would be fine, if ATOS/METEOGRID could add this Key-Column to the layer "LAND_USE_GRID".  (or replace the field "clarity:city", which has no external meaning)

**Comment by p-a-s-c-a-l** [comment]
@humerh @DanielRodera has the problem been resolved? 
Is this also related to [this problem](https://github.com/clarity-h2020/emikat/issues/40)?

**Comment by p-a-s-c-a-l** [comment]
any progress to report here?

**Comment by humerh** [comment]
NO, this problem is not yet solved!

Maybe it is simpler to provide a mapping table between the CITY number (here 248)  and the official CITY CODE (here AT001)
I assume, that the number 248 is an internal number in the postgresSQL database, but the CIYY_CODE is an offical identification of a specific city.
This would be simpler, than regeneration of the GIS database.

Currently I again use the name for the linkage of the information. But as we know this will not be successful  for each case.

**Comment by p-a-s-c-a-l** [comment]
That's the information is available in [the cities layer](https://geoserver.myclimateservice.eu/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Acity&bbox=1969465.0%2C996016.875%2C7168551.0%2C4677889.0&width=768&height=543&srs=EPSG%3A3035&styles=hw_availability&format=text%2Fhtml%3B%20subtype%3Dopenlayers#toggle):

fid | name | code | heat_wave | pluvial_flood | size
-- | -- | -- | -- | -- | --
city.244 | NAPOLI | IT003 | 6:32:33 AM | 12:07:45 AM | 6595

It contains the cities code. So this information **is** available and the city id (244) is the same. Now, wouldn't it be easily possible to add the same code to the [land_use_grid](https://geoserver.myclimateservice.eu/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Aland_use_grid&bbox=3082000.0%2C1638500.0%2C5564000.0%2C4282500.0&width=720&height=768&srs=EPSG%3A3035&format=application/openlayers) layer @DanielRodera ?

**Comment by humerh** [comment]
Very tricky to use the internal structure of the FID to get the info for this ID  👎
